// Auto-generated by scripts/generate-env.js. Do not edit by hand.
// Values are sourced from .env/.env.local files.

export const generatedEnvironment = {
  "hostUri": "https://localhost:8443",
  "aemUrl": "https://localhost:8443",
  "graphqlEndpoint": "/graphql/execute.json",
  "graphqlProject": "securbank",
  "ueServiceUrl": "https://localhost:8000",
  "corsOrigin": "https://experience.adobe.com",
  "localDevUrl": "https://localhost:3000",
  "repoTemplateUrl": "https://github.com/your-org/aem-ue-template",
  "useProxy": true,
  "authMethod": "basic",
  "basicAuthUser": "admin",
  "basicAuthPass": "admin",
  "siteName": "securbank",
  "aemGraphqlEndpoint": "https://localhost:8443/graphql/execute.json"
};
