#!/usr/bin/env node

/**
 * Build-time environment generator
 *
 * Loads values from .env/.env.local and writes them to
 * src/environments/environment.generated.ts so Angular can use them at build time.
 */

const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

const projectRoot = path.resolve(__dirname, '..');

// Load env files. .env.local overrides .env when both exist.
dotenv.config({ path: path.join(projectRoot, '.env') });
dotenv.config({ path: path.join(projectRoot, '.env.local') });

const outFile = path.join(projectRoot, 'src/environments/environment.generated.ts');

const envDefaults = {
  AEM_HOST_URI: 'https://localhost:8443',
  AEM_URL: process.env.AEM_HOST_URI || 'https://localhost:8443',
  GRAPHQL_ENDPOINT: '/graphql/execute.json',
  GRAPHQL_PROJECT: 'securbank',
  SITE_NAME: 'securbank',
  UNIVERSAL_EDITOR_SERVICE_URL: 'https://localhost:8000',
  CORS_ORIGIN: 'https://experience.adobe.com',
  LOCAL_DEV_URL: 'https://localhost:3000',
  REPO_TEMPLATE_URL: 'https://github.com/your-org/aem-ue-template',
  USE_PROXY: 'true',
  AUTH_METHOD: 'basic',
  BASIC_AUTH_USER: 'admin',
  BASIC_AUTH_PASS: 'admin',
};

const raw = {
  AEM_HOST_URI: process.env.AEM_HOST_URI,
  AEM_URL: process.env.AEM_URL,
  GRAPHQL_ENDPOINT: process.env.GRAPHQL_ENDPOINT,
  GRAPHQL_PROJECT: process.env.GRAPHQL_PROJECT,
  SITE_NAME: process.env.SITE_NAME,
  UNIVERSAL_EDITOR_SERVICE_URL: process.env.UNIVERSAL_EDITOR_SERVICE_URL,
  CORS_ORIGIN: process.env.CORS_ORIGIN,
  LOCAL_DEV_URL: process.env.LOCAL_DEV_URL,
  REPO_TEMPLATE_URL: process.env.REPO_TEMPLATE_URL,
  USE_PROXY: process.env.USE_PROXY,
  AUTH_METHOD: process.env.AUTH_METHOD,
  BASIC_AUTH_USER: process.env.BASIC_AUTH_USER,
  BASIC_AUTH_PASS: process.env.BASIC_AUTH_PASS,
};

function toBoolean(value, fallback) {
  if (typeof value === 'string') {
    const normalized = value.trim().toLowerCase();
    if (['true', '1', 'yes', 'y'].includes(normalized)) {
      return true;
    }
    if (['false', '0', 'no', 'n'].includes(normalized)) {
      return false;
    }
  }
  return fallback;
}

const resolved = {
  hostUri: raw.AEM_HOST_URI || envDefaults.AEM_HOST_URI,
  aemUrl: raw.AEM_URL || raw.AEM_HOST_URI || envDefaults.AEM_URL,
  graphqlEndpoint: raw.GRAPHQL_ENDPOINT || envDefaults.GRAPHQL_ENDPOINT,
  graphqlProject: raw.GRAPHQL_PROJECT || envDefaults.GRAPHQL_PROJECT,
  ueServiceUrl:
    raw.UNIVERSAL_EDITOR_SERVICE_URL || envDefaults.UNIVERSAL_EDITOR_SERVICE_URL,
  corsOrigin: raw.CORS_ORIGIN || envDefaults.CORS_ORIGIN,
  localDevUrl: raw.LOCAL_DEV_URL || envDefaults.LOCAL_DEV_URL,
  repoTemplateUrl: raw.REPO_TEMPLATE_URL || envDefaults.REPO_TEMPLATE_URL,
  useProxy: toBoolean(raw.USE_PROXY, envDefaults.USE_PROXY === 'true'),
  authMethod: (raw.AUTH_METHOD || envDefaults.AUTH_METHOD).toLowerCase(),
  basicAuthUser: raw.BASIC_AUTH_USER || envDefaults.BASIC_AUTH_USER,
  basicAuthPass: raw.BASIC_AUTH_PASS || envDefaults.BASIC_AUTH_PASS,
  siteName: raw.SITE_NAME || raw.GRAPHQL_PROJECT || envDefaults.SITE_NAME,
};

resolved.aemGraphqlEndpoint =
  process.env.AEM_GRAPHQL_ENDPOINT ||
  `${(resolved.hostUri || '').replace(/\/$/, '')}${resolved.graphqlEndpoint}`;

const generatedFile = `// Auto-generated by scripts/generate-env.js. Do not edit by hand.\n` +
  `// Values are sourced from .env/.env.local files.\n` +
  `\n` +
  `export const generatedEnvironment = ${JSON.stringify(resolved, null, 2)};\n`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, generatedFile, { encoding: 'utf8' });

console.log(`Environment file written to ${path.relative(projectRoot, outFile)}`);

